services:
  - type: web
    name: tarjeta-digital
    env: node
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: OWNER_PHONE
        value: "522311556138"
      - key: JWT_SECRET
        generateValue: true
